# Script de ayuda para Render.com
echo "🌐 DESPLIEGUE EN RENDER.COM (GRATIS)"
echo "===================================="

echo "Render.com es perfecto para tu bot de WhatsApp:"
echo "• 750 horas gratis por mes (más que suficiente)"
echo "• Despliegue automático desde GitHub"
echo "• Sin límites de ancho de banda"
echo "• SSL automático incluido"
echo ""

echo "PASOS RÁPIDOS:"
echo "1. Ve a https://render.com"
echo "2. Sign up/Login con GitHub"
echo "3. Dashboard → New → Web Service"
echo "4. Connect: Joaquinagm01/botConvenios"
echo "5. Configurar:"
echo "   - Runtime: Python"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: gunicorn --bind 0.0.0.0:\$PORT app:app"
echo "6. Environment Variables:"
echo "   - TWILIO_ACCOUNT_SID: [tu_account_sid]"
echo "   - TWILIO_AUTH_TOKEN: [tu_auth_token]"
echo "   - TWILIO_WHATSAPP_NUMBER: whatsapp:+14155238886"
echo "   - FLASK_ENV: production"
echo "   - SECRET_KEY: mi-clave-super-secreta-2025"
echo "7. Create Web Service"
echo ""

echo "¡Listo! Render te da una URL como:"
echo "https://tu-bot-convenios.onrender.com"
echo ""

echo "Configura esa URL en Twilio:"
echo "https://www.twilio.com/console → Messaging → Settings → WhatsApp → Sandbox"
echo "Webhook URL: https://tu-url.onrender.com/whatsapp"
